import { sql } from "drizzle-orm";
import {
  date,
  datetime,
  decimal,
  index,
  int,
  json,
  mysqlEnum,
  mysqlTable,
  text,
  tinyint,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";

export const hfListings = mysqlTable("hf_listings", {
  id: int("id").autoincrement().primaryKey(),
  slug: varchar("slug", { length: 190 }).notNull(),
  userId: varchar("user_id", { length: 36 }),
  firmId: int("firm_id"),
  listingType: mysqlEnum("listing_type", ["satis", "alim"]).notNull().default("satis"),
  partyRole: mysqlEnum("party_role", ["uretici", "komisyoncu", "alici", "diger"]).notNull().default("uretici"),
  productId: int("product_id"),
  productSlug: varchar("product_slug", { length: 128 }),
  productName: varchar("product_name", { length: 255 }).notNull(),
  categorySlug: varchar("category_slug", { length: 64 }).notNull().default("diger"),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  quality: varchar("quality", { length: 96 }),
  packaging: varchar("packaging", { length: 96 }),
  quantity: decimal("quantity", { precision: 14, scale: 2 }),
  quantityUnit: varchar("quantity_unit", { length: 32 }).notNull().default("kg"),
  priceType: mysqlEnum("price_type", ["sabit", "pazarlik", "hal_endeksli"]).notNull().default("sabit"),
  priceMin: decimal("price_min", { precision: 12, scale: 2 }),
  priceMax: decimal("price_max", { precision: 12, scale: 2 }),
  priceUnit: varchar("price_unit", { length: 32 }).notNull().default("kg"),
  halIndexPct: decimal("hal_index_pct", { precision: 6, scale: 2 }),
  currency: varchar("currency", { length: 8 }).notNull().default("TRY"),
  citySlug: varchar("city_slug", { length: 96 }),
  districtSlug: varchar("district_slug", { length: 128 }),
  contactName: varchar("contact_name", { length: 255 }),
  contactPhone: varchar("contact_phone", { length: 128 }),
  phoneVerified: tinyint("phone_verified").notNull().default(0),
  hidePhone: tinyint("hide_phone").notNull().default(0),
  validUntil: date("valid_until", { mode: "string" }).notNull(),
  status: mysqlEnum("status", ["pending", "approved", "rejected", "expired", "closed"]).notNull().default("pending"),
  moderationNote: text("moderation_note"),
  isSuspicious: tinyint("is_suspicious").notNull().default(0),
  isFeatured: tinyint("is_featured").notNull().default(0),
  featuredUntil: datetime("featured_until", { fsp: 3 }),
  viewCount: int("view_count").notNull().default(0),
  source: mysqlEnum("source", ["user", "telegram", "whatsapp", "assisted", "seed"]).notNull().default("user"),
  createdBy: varchar("created_by", { length: 36 }),
  raw: json("raw").$type<Record<string, unknown>>(),
  createdAt: datetime("created_at", { fsp: 3 }).default(sql`CURRENT_TIMESTAMP(3)`),
  updatedAt: datetime("updated_at", { fsp: 3 }).default(sql`CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)`),
}, (t) => [
  uniqueIndex("hf_listings_slug_uq").on(t.slug),
  index("hf_listings_city_idx").on(t.citySlug, t.districtSlug),
  index("hf_listings_product_idx").on(t.productSlug),
  index("hf_listings_type_status_idx").on(t.listingType, t.status, t.validUntil),
  index("hf_listings_featured_idx").on(t.isFeatured, t.featuredUntil),
  index("hf_listings_user_idx").on(t.userId),
]);

export const hfListingInquiries = mysqlTable("hf_listing_inquiries", {
  id: int("id").autoincrement().primaryKey(),
  listingId: int("listing_id").notNull(),
  userId: varchar("user_id", { length: 36 }),
  name: varchar("name", { length: 255 }),
  phone: varchar("phone", { length: 128 }),
  message: text("message"),
  offerPrice: decimal("offer_price", { precision: 12, scale: 2 }),
  status: mysqlEnum("status", ["new", "contacted", "closed"]).notNull().default("new"),
  createdAt: datetime("created_at", { fsp: 3 }).default(sql`CURRENT_TIMESTAMP(3)`),
  updatedAt: datetime("updated_at", { fsp: 3 }).default(sql`CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)`),
}, (t) => [
  index("hf_listing_inquiries_listing_idx").on(t.listingId),
  index("hf_listing_inquiries_status_idx").on(t.status, t.createdAt),
]);

export const hfListingImages = mysqlTable("hf_listing_images", {
  id: int("id").autoincrement().primaryKey(),
  listingId: int("listing_id").notNull(),
  url: varchar("url", { length: 512 }).notNull(),
  displayOrder: int("display_order").notNull().default(100),
  createdAt: datetime("created_at", { fsp: 3 }).default(sql`CURRENT_TIMESTAMP(3)`),
}, (t) => [
  index("hf_listing_images_listing_idx").on(t.listingId),
]);

export const hfPhoneVerifications = mysqlTable("hf_phone_verifications", {
  id: int("id").autoincrement().primaryKey(),
  phone: varchar("phone", { length: 32 }).notNull(),
  code: varchar("code", { length: 8 }).notNull(),
  purpose: mysqlEnum("purpose", ["listing", "signup", "claim"]).notNull().default("listing"),
  attempts: int("attempts").notNull().default(0),
  verifiedAt: datetime("verified_at", { fsp: 3 }),
  expiresAt: datetime("expires_at", { fsp: 3 }).notNull(),
  createdAt: datetime("created_at", { fsp: 3 }).default(sql`CURRENT_TIMESTAMP(3)`),
}, (t) => [
  index("hf_phone_verifications_phone_idx").on(t.phone, t.purpose, t.expiresAt),
]);
