CREATE TABLE IF NOT EXISTS hf_firms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(32) NOT NULL,
  slug VARCHAR(180) NOT NULL,
  name VARCHAR(255) NOT NULL,
  contact_person VARCHAR(255) NULL,
  phone VARCHAR(128) NULL,
  address TEXT NULL,
  city_slug VARCHAR(96) NULL,
  district_slug VARCHAR(128) NULL,
  photo_url VARCHAR(512) NULL,
  source_url VARCHAR(512) NOT NULL,
  firm_type ENUM('komisyoncu', 'soguk_hava', 'nakliye', 'zirai_ilac') NOT NULL DEFAULT 'komisyoncu',
  categories JSON NULL,
  owner_user_id VARCHAR(36) NULL,
  source ENUM('halkatalogu','user') NOT NULL DEFAULT 'halkatalogu',
  status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'approved',
  description TEXT NULL,
  claim_status ENUM('unclaimed','pending','verified') NOT NULL DEFAULT 'unclaimed',
  is_active TINYINT NOT NULL DEFAULT 1,
  seo_index TINYINT NOT NULL DEFAULT 0 COMMENT 'Sitemap+index havuzu; 1 = zengin/onayli firma (varsayilan 0=noindex)',
  first_seen_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  last_seen_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  raw JSON NULL,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY hf_firms_external_uq (external_id),
  UNIQUE KEY hf_firms_slug_uq (slug),
  KEY hf_firms_city_idx (city_slug, district_slug),
  KEY hf_firms_type_idx (firm_type, is_active),
  KEY hf_firms_seo_idx (seo_index, city_slug),
  KEY hf_firms_owner_idx (owner_user_id),
  KEY hf_firms_status_idx (status, source),
  KEY hf_firms_claim_status_idx (claim_status),
  KEY hf_firms_seen_idx (last_seen_at)
);

CREATE TABLE IF NOT EXISTS hf_firm_products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firm_id INT NOT NULL,
  product_slug VARCHAR(128) NULL,
  product_name VARCHAR(255) NOT NULL,
  note VARCHAR(500) NULL,
  price VARCHAR(128) NULL,
  display_order INT NOT NULL DEFAULT 100,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT hf_firm_products_firm_fk FOREIGN KEY (firm_id) REFERENCES hf_firms(id) ON DELETE CASCADE,
  KEY hf_firm_products_firm_idx (firm_id),
  KEY hf_firm_products_product_idx (product_slug)
);

CREATE TABLE IF NOT EXISTS hf_firm_prices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firm_id INT NOT NULL,
  product_slug VARCHAR(128) NULL,
  product_name VARCHAR(255) NOT NULL,
  unit VARCHAR(32) NOT NULL DEFAULT 'kg',
  min_price DECIMAL(12,2) NULL,
  max_price DECIMAL(12,2) NULL,
  avg_price DECIMAL(12,2) NOT NULL,
  recorded_date DATE NOT NULL,
  is_suspicious TINYINT(1) NOT NULL DEFAULT 0,
  created_by VARCHAR(36) NULL,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT hf_firm_prices_firm_fk FOREIGN KEY (firm_id) REFERENCES hf_firms(id) ON DELETE CASCADE,
  UNIQUE KEY hf_firm_prices_uq (firm_id, product_name, recorded_date),
  KEY hf_firm_prices_firm_date_idx (firm_id, recorded_date),
  KEY hf_firm_prices_product_idx (product_slug)
);

CREATE TABLE IF NOT EXISTS hf_firm_claims (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firm_id INT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  evidence TEXT NULL,
  reviewed_by VARCHAR(36) NULL,
  reviewed_at DATETIME(3) NULL,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT hf_firm_claims_firm_fk FOREIGN KEY (firm_id) REFERENCES hf_firms(id) ON DELETE CASCADE,
  KEY hf_firm_claims_firm_idx (firm_id),
  KEY hf_firm_claims_user_idx (user_id),
  KEY hf_firm_claims_status_idx (status, created_at)
);

CREATE TABLE IF NOT EXISTS hf_firm_deals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firm_id INT NOT NULL,
  status ENUM('lead', 'contacted', 'negotiating', 'won', 'lost') NOT NULL DEFAULT 'lead',
  deal_type ENUM('reklam', 'sponsorluk', 'premium', 'diger') NOT NULL DEFAULT 'reklam',
  value DECIMAL(12,2) NULL,
  currency VARCHAR(8) NOT NULL DEFAULT 'TRY',
  owner VARCHAR(128) NULL,
  notes TEXT NULL,
  contacted_at DATETIME(3) NULL,
  next_action_at DATETIME(3) NULL,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT hf_firm_deals_firm_fk FOREIGN KEY (firm_id) REFERENCES hf_firms(id) ON DELETE CASCADE,
  KEY hf_firm_deals_firm_idx (firm_id),
  KEY hf_firm_deals_status_idx (status, next_action_at)
);

CREATE TABLE IF NOT EXISTS hf_firm_sponsorships (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firm_id INT NOT NULL,
  tier VARCHAR(32) NOT NULL DEFAULT 'standard',
  placement ENUM('il', 'kategori', 'global') NOT NULL DEFAULT 'il',
  placement_slug VARCHAR(128) NULL,
  starts_at DATETIME(3) NOT NULL,
  ends_at DATETIME(3) NOT NULL,
  is_active TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT hf_firm_sponsorships_firm_fk FOREIGN KEY (firm_id) REFERENCES hf_firms(id) ON DELETE CASCADE,
  KEY hf_firm_sponsorships_firm_idx (firm_id),
  KEY hf_firm_sponsorships_active_idx (is_active, placement, placement_slug, starts_at, ends_at)
);
