SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `tweets` (
  `id` CHAR(36) NOT NULL,
  `platform` VARCHAR(24) NOT NULL DEFAULT 'twitter',
  `content` TEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'sent',
  `source` VARCHAR(32) NOT NULL DEFAULT 'manual',
  `template` VARCHAR(50) NULL,
  `post_format` VARCHAR(16) NOT NULL DEFAULT 'post',
  `media_url` TEXT NULL,
  `source_ref` VARCHAR(190) NULL,
  `scheduled_at` DATETIME NULL,
  `posted_at` DATETIME NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `locked_at` DATETIME NULL,
  `x_tweet_id` VARCHAR(64) NULL,
  `external_post_id` VARCHAR(128) NULL,
  `error_message` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tweets_x_tweet_id` (`x_tweet_id`),
  UNIQUE KEY `uq_tweets_source_ref` (`source_ref`),
  KEY `idx_tweets_platform_status_sched` (`platform`, `status`, `scheduled_at`),
  KEY `idx_tweets_status_sched` (`status`, `scheduled_at`),
  KEY `idx_tweets_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `social_content_plans` (
  `id` CHAR(36) NOT NULL,
  `platform` VARCHAR(24) NOT NULL,
  `slot_key` VARCHAR(64) NOT NULL,
  `day_of_week` INT NOT NULL,
  `hour` INT NOT NULL,
  `minute` INT NOT NULL DEFAULT 0,
  `template` VARCHAR(50) NOT NULL,
  `pillar` VARCHAR(100) NULL,
  `topic` VARCHAR(255) NULL,
  `preferred_product` VARCHAR(120) NULL,
  `post_format` VARCHAR(16) NOT NULL DEFAULT 'post',
  `media_required` INT NOT NULL DEFAULT 0,
  `is_active` INT NOT NULL DEFAULT 1,
  `order_index` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_scp_platform_slot` (`platform`, `slot_key`),
  KEY `idx_scp_platform_active` (`platform`, `is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `popups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL,
  `type` VARCHAR(30) NOT NULL DEFAULT 'topbar',
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `background_color` VARCHAR(30) NULL,
  `text_color` VARCHAR(30) NULL,
  `button_text` VARCHAR(100) NULL,
  `button_color` VARCHAR(30) NULL,
  `button_hover_color` VARCHAR(30) NULL,
  `button_text_color` VARCHAR(30) NULL,
  `link_url` VARCHAR(500) NULL,
  `link_target` VARCHAR(20) NOT NULL DEFAULT '_self',
  `target_paths` TEXT NULL,
  `image_url` TEXT NULL,
  `image_asset_id` CHAR(36) NULL,
  `alt` VARCHAR(255) NULL,
  `text_behavior` VARCHAR(20) NOT NULL DEFAULT 'marquee',
  `scroll_speed` INT UNSIGNED NOT NULL DEFAULT 60,
  `closeable` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `delay_seconds` INT UNSIGNED NOT NULL DEFAULT 0,
  `display_frequency` VARCHAR(20) NOT NULL DEFAULT 'always',
  `is_active` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `display_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `start_at` DATETIME(3) NULL,
  `end_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_popup_uuid` (`uuid`),
  KEY `idx_popup_type` (`type`),
  KEY `idx_popup_active` (`is_active`),
  KEY `idx_popup_order` (`display_order`),
  KEY `idx_popup_img_asset` (`image_asset_id`),
  CONSTRAINT `fk_popup_image_asset`
    FOREIGN KEY (`image_asset_id`) REFERENCES `storage_assets` (`id`)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `popups_i18n` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `popup_id` INT UNSIGNED NOT NULL,
  `locale` VARCHAR(10) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `button_text` VARCHAR(100) NULL,
  `alt` VARCHAR(255) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_popup_i18n_popup_locale` (`popup_id`, `locale`),
  KEY `idx_popup_i18n_locale` (`locale`),
  KEY `idx_popup_i18n_title` (`title`),
  CONSTRAINT `fk_popup_i18n_popup`
    FOREIGN KEY (`popup_id`) REFERENCES `popups` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `site_settings` (`id`, `key`, `locale`, `value`) VALUES
(UUID(), 'twitter_enabled', '*', 'false'),
(UUID(), 'twitter_api_key', '*', '""'),
(UUID(), 'twitter_api_secret', '*', '""'),
(UUID(), 'twitter_access_token', '*', '""'),
(UUID(), 'twitter_access_token_secret', '*', '""'),
(UUID(), 'facebook_enabled', '*', 'false'),
(UUID(), 'facebook_page_id', '*', '""'),
(UUID(), 'facebook_page_access_token', '*', '""'),
(UUID(), 'instagram_enabled', '*', 'false'),
(UUID(), 'instagram_business_account_id', '*', '""'),
(UUID(), 'instagram_access_token', '*', '""'),
(UUID(), 'linkedin_enabled', '*', 'false'),
(UUID(), 'linkedin_organization_urn', '*', '""'),
(UUID(), 'linkedin_access_token', '*', '""'),
(UUID(), 'youtube_enabled', '*', 'false'),
(UUID(), 'youtube_channel_id', '*', '""'),
(UUID(), 'youtube_access_token', '*', '""'),
(UUID(), 'meta_enabled', '*', 'false'),
(UUID(), 'meta_pixel_id', '*', '""'),
(UUID(), 'meta_capi_token', '*', '""'),
(UUID(), 'meta_test_event_code', '*', '""'),
(UUID(), 'google_ads_enabled', '*', 'false'),
(UUID(), 'google_ads_developer_token', '*', '""'),
(UUID(), 'google_ads_client_id', '*', '""'),
(UUID(), 'google_ads_client_secret', '*', '""'),
(UUID(), 'google_ads_refresh_token', '*', '""'),
(UUID(), 'google_ads_customer_id', '*', '"7020334476"'),
(UUID(), 'google_ads_login_customer_id', '*', '"5200994833"'),
(UUID(), 'google_oauth_redirect', '*', '"https://haldefiyat.com/admin/google-connect/callback"'),
(UUID(), 'google_oauth_connected_at', '*', '""')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);
