CREATE TABLE IF NOT EXISTS hf_banners (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  position VARCHAR(64) NOT NULL,
  title VARCHAR(190) NOT NULL,
  advertiser VARCHAR(160) NULL,
  notes VARCHAR(500) NULL,
  type ENUM('image','code') NOT NULL DEFAULT 'image',
  image_url VARCHAR(512) NULL,
  alt VARCHAR(255) NULL,
  link_url VARCHAR(500) NULL,
  link_target VARCHAR(20) NOT NULL DEFAULT '_blank',
  rel VARCHAR(64) NOT NULL DEFAULT 'sponsored nofollow noopener',
  code TEXT NULL,
  device ENUM('all','desktop','mobile') NOT NULL DEFAULT 'all',
  weight INT UNSIGNED NOT NULL DEFAULT 1,
  display_order INT NOT NULL DEFAULT 0,
  is_active TINYINT NOT NULL DEFAULT 0,
  start_at DATETIME(3) NULL,
  end_at DATETIME(3) NULL,
  impressions INT UNSIGNED NOT NULL DEFAULT 0,
  clicks INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY hf_banners_pos_idx (position, is_active, display_order),
  KEY hf_banners_active_idx (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
