CREATE TABLE IF NOT EXISTS `hf_price_quarantine` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `market_id` INT UNSIGNED NOT NULL,
  `recorded_date` DATE NOT NULL,
  `source_api` VARCHAR(64) NOT NULL,
  `unit` VARCHAR(32) NOT NULL,
  `min_price` DECIMAL(12,2) NULL,
  `max_price` DECIMAL(12,2) NULL,
  `avg_price` DECIMAL(12,2) NOT NULL,
  `reason_code` VARCHAR(64) NOT NULL,
  `severity` ENUM('warning','critical') NOT NULL,
  `confidence` DECIMAL(5,4) NOT NULL,
  `peer_median` DECIMAL(12,2) NULL,
  `deviation_ratio` DECIMAL(12,4) NULL,
  `status` ENUM('pending','approved','rejected','corrected') NOT NULL DEFAULT 'pending',
  `review_note` TEXT NULL,
  `reviewed_by` VARCHAR(36) NULL,
  `reviewed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `hf_pq_record_uq` (`product_id`,`market_id`,`recorded_date`,`source_api`,`reason_code`),
  KEY `hf_pq_status_created_idx` (`status`,`created_at`),
  KEY `hf_pq_severity_idx` (`severity`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
