CREATE TABLE IF NOT EXISTS `hf_product_review_queue` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_api` VARCHAR(64) NOT NULL,
  `market_id` INT UNSIGNED NULL,
  `raw_name` VARCHAR(255) NOT NULL,
  `normalized_name` VARCHAR(255) NOT NULL,
  `raw_category` VARCHAR(128) NULL,
  `suggested_category` VARCHAR(64) NOT NULL DEFAULT 'diger',
  `raw_unit` VARCHAR(64) NULL,
  `canonical_unit` VARCHAR(32) NULL,
  `match_key` VARCHAR(320) NULL,
  `recorded_date` DATE NOT NULL,
  `min_price` DECIMAL(12,2) NULL,
  `max_price` DECIMAL(12,2) NULL,
  `avg_price` DECIMAL(12,2) NULL,
  `reason_code` ENUM('UNKNOWN_PRODUCT','UNKNOWN_UNIT') NOT NULL,
  `status` ENUM('pending','aliased','created','rejected') NOT NULL DEFAULT 'pending',
  `target_product_id` INT UNSIGNED NULL,
  `occurrence_count` INT UNSIGNED NOT NULL DEFAULT 1,
  `first_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `review_note` TEXT NULL,
  `reviewed_by` VARCHAR(36) NULL,
  `reviewed_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `hf_prq_pending_key_uq` (`source_api`,`market_id`,`normalized_name`,`raw_unit`,`status`),
  KEY `hf_prq_status_age_idx` (`status`,`first_seen_at`),
  KEY `hf_prq_reason_idx` (`reason_code`,`last_seen_at`),
  KEY `hf_prq_target_idx` (`target_product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
